/*
 * Kintsugi Voice v2 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kintsugi.client.openapi.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * PredictionActualScoreFeedback
 */
@JsonPropertyOrder({
  PredictionActualScoreFeedback.JSON_PROPERTY_ANXIETY_BINARY,
  PredictionActualScoreFeedback.JSON_PROPERTY_DEPRESSION_BINARY,
  PredictionActualScoreFeedback.JSON_PROPERTY_PHQ2,
  PredictionActualScoreFeedback.JSON_PROPERTY_PHQ9
})
@JsonTypeName("prediction.ActualScoreFeedback")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-05-16T23:40:17.598272-03:00[America/Fortaleza]", comments = "Generator version: 7.5.0")
public class PredictionActualScoreFeedback {
  public static final String JSON_PROPERTY_ANXIETY_BINARY = "anxiety_binary";
  private PredictionValidBinaryString anxietyBinary;

  public static final String JSON_PROPERTY_DEPRESSION_BINARY = "depression_binary";
  private PredictionValidBinaryString depressionBinary;

  public static final String JSON_PROPERTY_PHQ2 = "phq_2";
  private List<PredictionValidPHQInt> phq2 = new ArrayList<>();

  public static final String JSON_PROPERTY_PHQ9 = "phq_9";
  private List<PredictionValidPHQInt> phq9 = new ArrayList<>();

  public PredictionActualScoreFeedback() {
  }

  public PredictionActualScoreFeedback anxietyBinary(PredictionValidBinaryString anxietyBinary) {
    
    this.anxietyBinary = anxietyBinary;
    return this;
  }

   /**
   * Get anxietyBinary
   * @return anxietyBinary
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ANXIETY_BINARY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PredictionValidBinaryString getAnxietyBinary() {
    return anxietyBinary;
  }


  @JsonProperty(JSON_PROPERTY_ANXIETY_BINARY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAnxietyBinary(PredictionValidBinaryString anxietyBinary) {
    this.anxietyBinary = anxietyBinary;
  }


  public PredictionActualScoreFeedback depressionBinary(PredictionValidBinaryString depressionBinary) {
    
    this.depressionBinary = depressionBinary;
    return this;
  }

   /**
   * Get depressionBinary
   * @return depressionBinary
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEPRESSION_BINARY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PredictionValidBinaryString getDepressionBinary() {
    return depressionBinary;
  }


  @JsonProperty(JSON_PROPERTY_DEPRESSION_BINARY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDepressionBinary(PredictionValidBinaryString depressionBinary) {
    this.depressionBinary = depressionBinary;
  }


  public PredictionActualScoreFeedback phq2(List<PredictionValidPHQInt> phq2) {
    
    this.phq2 = phq2;
    return this;
  }

  public PredictionActualScoreFeedback addPhq2Item(PredictionValidPHQInt phq2Item) {
    if (this.phq2 == null) {
      this.phq2 = new ArrayList<>();
    }
    this.phq2.add(phq2Item);
    return this;
  }

   /**
   * Get phq2
   * @return phq2
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PHQ2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PredictionValidPHQInt> getPhq2() {
    return phq2;
  }


  @JsonProperty(JSON_PROPERTY_PHQ2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhq2(List<PredictionValidPHQInt> phq2) {
    this.phq2 = phq2;
  }


  public PredictionActualScoreFeedback phq9(List<PredictionValidPHQInt> phq9) {
    
    this.phq9 = phq9;
    return this;
  }

  public PredictionActualScoreFeedback addPhq9Item(PredictionValidPHQInt phq9Item) {
    if (this.phq9 == null) {
      this.phq9 = new ArrayList<>();
    }
    this.phq9.add(phq9Item);
    return this;
  }

   /**
   * Get phq9
   * @return phq9
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PHQ9)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PredictionValidPHQInt> getPhq9() {
    return phq9;
  }


  @JsonProperty(JSON_PROPERTY_PHQ9)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhq9(List<PredictionValidPHQInt> phq9) {
    this.phq9 = phq9;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PredictionActualScoreFeedback predictionActualScoreFeedback = (PredictionActualScoreFeedback) o;
    return Objects.equals(this.anxietyBinary, predictionActualScoreFeedback.anxietyBinary) &&
        Objects.equals(this.depressionBinary, predictionActualScoreFeedback.depressionBinary) &&
        Objects.equals(this.phq2, predictionActualScoreFeedback.phq2) &&
        Objects.equals(this.phq9, predictionActualScoreFeedback.phq9);
  }

  @Override
  public int hashCode() {
    return Objects.hash(anxietyBinary, depressionBinary, phq2, phq9);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PredictionActualScoreFeedback {\n");
    sb.append("    anxietyBinary: ").append(toIndentedString(anxietyBinary)).append("\n");
    sb.append("    depressionBinary: ").append(toIndentedString(depressionBinary)).append("\n");
    sb.append("    phq2: ").append(toIndentedString(phq2)).append("\n");
    sb.append("    phq9: ").append(toIndentedString(phq9)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

