/*
 * Kintsugi Voice v2 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kintsugi.client.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets session.Gender
 */
public enum SessionGender {
  
  MALE_GENDER("male"),
  
  FEMALE_GENDER("female"),
  
  NONBINARY_GENDER("non-binary"),
  
  TRANSGENDER_FEMALE_GENDER("transgender female"),
  
  TRANSGENDER_MALE_GENDER("transgender male"),
  
  OTHER_GENDER("other"),
  
  PREFER_NOT_TO_SPECIFY_GENDER("prefer not to specify");

  private String value;

  SessionGender(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static SessionGender fromValue(String value) {
    for (SessionGender b : SessionGender.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

