/*
 * Kintsugi Voice v2 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kintsugihealth.client.openapi.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * SessionSessionMetadata
 */
@JsonPropertyOrder({
  SessionSessionMetadata.JSON_PROPERTY_AGE,
  SessionSessionMetadata.JSON_PROPERTY_ETHNICITY,
  SessionSessionMetadata.JSON_PROPERTY_GENDER,
  SessionSessionMetadata.JSON_PROPERTY_LANGUAGE,
  SessionSessionMetadata.JSON_PROPERTY_RACE,
  SessionSessionMetadata.JSON_PROPERTY_WEIGHT,
  SessionSessionMetadata.JSON_PROPERTY_ZIPCODE
})
@JsonTypeName("session.SessionMetadata")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-05-16T23:40:17.598272-03:00[America/Fortaleza]", comments = "Generator version: 7.5.0")
public class SessionSessionMetadata {
  public static final String JSON_PROPERTY_AGE = "age";
  private Integer age;

  public static final String JSON_PROPERTY_ETHNICITY = "ethnicity";
  private SessionEthnicity ethnicity;

  public static final String JSON_PROPERTY_GENDER = "gender";
  private SessionGender gender;

  public static final String JSON_PROPERTY_LANGUAGE = "language";
  private Boolean language;

  public static final String JSON_PROPERTY_RACE = "race";
  private SessionRace race;

  public static final String JSON_PROPERTY_WEIGHT = "weight";
  private Integer weight;

  public static final String JSON_PROPERTY_ZIPCODE = "zipcode";
  private String zipcode;

  public SessionSessionMetadata() {
  }

  public SessionSessionMetadata age(Integer age) {
    
    this.age = age;
    return this;
  }

   /**
   * Get age
   * @return age
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAge() {
    return age;
  }


  @JsonProperty(JSON_PROPERTY_AGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAge(Integer age) {
    this.age = age;
  }


  public SessionSessionMetadata ethnicity(SessionEthnicity ethnicity) {
    
    this.ethnicity = ethnicity;
    return this;
  }

   /**
   * Get ethnicity
   * @return ethnicity
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ETHNICITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SessionEthnicity getEthnicity() {
    return ethnicity;
  }


  @JsonProperty(JSON_PROPERTY_ETHNICITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEthnicity(SessionEthnicity ethnicity) {
    this.ethnicity = ethnicity;
  }


  public SessionSessionMetadata gender(SessionGender gender) {
    
    this.gender = gender;
    return this;
  }

   /**
   * Get gender
   * @return gender
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GENDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SessionGender getGender() {
    return gender;
  }


  @JsonProperty(JSON_PROPERTY_GENDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGender(SessionGender gender) {
    this.gender = gender;
  }


  public SessionSessionMetadata language(Boolean language) {
    
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getLanguage() {
    return language;
  }


  @JsonProperty(JSON_PROPERTY_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLanguage(Boolean language) {
    this.language = language;
  }


  public SessionSessionMetadata race(SessionRace race) {
    
    this.race = race;
    return this;
  }

   /**
   * Get race
   * @return race
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RACE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SessionRace getRace() {
    return race;
  }


  @JsonProperty(JSON_PROPERTY_RACE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRace(SessionRace race) {
    this.race = race;
  }


  public SessionSessionMetadata weight(Integer weight) {
    
    this.weight = weight;
    return this;
  }

   /**
   * Get weight
   * @return weight
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getWeight() {
    return weight;
  }


  @JsonProperty(JSON_PROPERTY_WEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWeight(Integer weight) {
    this.weight = weight;
  }


  public SessionSessionMetadata zipcode(String zipcode) {
    
    this.zipcode = zipcode;
    return this;
  }

   /**
   * Get zipcode
   * @return zipcode
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ZIPCODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getZipcode() {
    return zipcode;
  }


  @JsonProperty(JSON_PROPERTY_ZIPCODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setZipcode(String zipcode) {
    this.zipcode = zipcode;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SessionSessionMetadata sessionSessionMetadata = (SessionSessionMetadata) o;
    return Objects.equals(this.age, sessionSessionMetadata.age) &&
        Objects.equals(this.ethnicity, sessionSessionMetadata.ethnicity) &&
        Objects.equals(this.gender, sessionSessionMetadata.gender) &&
        Objects.equals(this.language, sessionSessionMetadata.language) &&
        Objects.equals(this.race, sessionSessionMetadata.race) &&
        Objects.equals(this.weight, sessionSessionMetadata.weight) &&
        Objects.equals(this.zipcode, sessionSessionMetadata.zipcode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(age, ethnicity, gender, language, race, weight, zipcode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SessionSessionMetadata {\n");
    sb.append("    age: ").append(toIndentedString(age)).append("\n");
    sb.append("    ethnicity: ").append(toIndentedString(ethnicity)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    race: ").append(toIndentedString(race)).append("\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("    zipcode: ").append(toIndentedString(zipcode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

