/*
 * Kintsugi Voice v2 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kintsugihealth.client.openapi.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets session.Ethnicity
 */
public enum SessionEthnicity {
  
  IS_SPANISH_ORIGIN_ETHNICITY("Hispanic, Latino, or Spanish Origin"),
  
  NOT_SPANISH_ORIGIN_ETHNICITY("Not Hispanic, Latino, or Spanish Origin");

  private String value;

  SessionEthnicity(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static SessionEthnicity fromValue(String value) {
    for (SessionEthnicity b : SessionEthnicity.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

