/*
 * Kintsugi Voice v2 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kintsugihealth.client.openapi.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets session.Race
 */
public enum SessionRace {
  
  WHITE_RACE("white"),
  
  BLACK_OR_AA_RACE("black or african-american"),
  
  ASIAN_RACE("asian"),
  
  AM_INDIGENOUS_RACE("american indian or alaskan native"),
  
  PAC_INDIGINEOUS_RACE("native Hawaiian or pacific islander"),
  
  TWO_OR_MORE_RACE("two or more races"),
  
  OTHER_RACE("other"),
  
  PREFER_NOT_TO_SPECIFY_RACE("prefer not to specify");

  private String value;

  SessionRace(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static SessionRace fromValue(String value) {
    for (SessionRace b : SessionRace.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

